import localFont from 'next/font/local'
import Header from './components/Header'
import Footer from "./components/Footer"
import Distressed from '../../public/images/distressed.jpg'

import "./globals.css";

const wilson_wells = localFont({
  src:"./fonts/Wilson-wells.woff2",
  variable:"--font-wilson-wells",
  display:"swap",
})

const gin_lines = localFont({
  src:"./fonts/Gin-Lines.woff2",
  variable:"--font-gin-lines",
  display:"swap",
})

const gin_regular = localFont({
  src:"./fonts/Gin-regular.woff2",
  variable:"--font-gin-regular",
  display:"swap",
})

export const metadata = {
  title: "Welcome Aboard | The Standard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${wilson_wells.variable} ${gin_lines.variable} ${gin_regular.variable}`}>      
      <body className={'bg-black text-smoke relative'}>    
        <Header/>
        <main className='relative z-20'>
          {children}
        </main>
        <Footer/>
        <div className="h-full w-full fixed top-0 left-0 z-0 bg-cover bg-no-repeat bg-center" style={{ backgroundImage: `url(${Distressed.src})` }}></div>
      </body>
    </html>
  );
}